sudo: required
language: python
services:
- docker
before_deploy:
- docker build -t idelab/datalab-language-api:$TRAVIS_TAG .
deploy:
    provider: script
    script: ./deploy.sh
    on:
        tags: true